all:
  hosts:
    bastion:
      ansible_connection: local
    allinone:
      ansible_host: 127.0.0.1
  vars:
    zuul_tenant_name: openlaballinone
  children:
    nodepool:
      children:
        nodepool-builder:
          hosts: allinone
        nodepool-launcher:
          hosts: allinone
    zuul:
      children:
        zuul-scheduler:
          hosts: allinone
        zuul-executor:
          hosts: allinone
        zuul-web:
          hosts: allinone
        zuul-merger:
          hosts: allinone
        zuul-fingergw:
          hosts: allinone
        zuul-log-server:
          hosts: allinone
      vars:
        github_app_id: 7102
        github_app_key_file: "{{ labkeeper_config_git_dest }}/zuul/liu-openlab-ci.pem"
        github_webhook_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35353637626332663562663964363936346533326332626366633965333164306366656635323835
          3730623134613431613461303638346564616538643863660a343764653761393062366130616362
          36616236643135623465643538653764373635623766366263323639643033306661373736653766
          3838656339306637660a363762343431633061643364633932336565313632643539656565383034
          6162
        zuul_file_main_yaml_src: "{{ labkeeper_config_git_dest }}/zuul/allinone-main.yaml"
        github_acc_token:
        github_zuul_ssh_key_name: "pub key for openlaballinone"
        zuul_tenant_name: openlaballinone
        zuul_public_ip: 80.158.7.210
        openlab_zuul_jobs_key_src: "{{ labkeeper_config_git_dest }}/zuul/allinone-openlab-zuul-jobs.pem"
        openlab_zuul_jobs_key_dest: "/var/lib/zuul/keys/github/liu-sheng/openlab-zuul-jobs.pem"
    gear:
      hosts: allinone
    statsd:
      hosts: allinone
    zookeeper:
      hosts: allinone
    mysql:
      hosts: allinone
    apache:
      hosts: allinone
