all:
  hosts:
    bastion:
      ansible_connection: local
    allinone01:
      ansible_host: 192.168.211.20
    allinone02:
      ansible_host: 192.168.211.174
    zk03:
      ansible_host: 192.168.211.151
  vars:
    zuul_tenant_name: openlaballinone
    zookeeper_ha_mode: true
  children:
    nodepool:
      children:
        nodepool-builder:
          children:
            nodepool-builder-master:
              hosts: allinone01
            nodepool-builder-slave:
              hosts: allinone02
              vars:
                service_state: stopped
          vars:
            nodepool_builder_id: "8fcf0492-b972-45cc-828f-efd6b301b46e"
        nodepool-launcher:
          children:
            nodepool-launcher-master:
              hosts: allinone01
            nodepool-launcher-slave:
              hosts: allinone02
              vars:
                service_state: stopped
      vars:
        nodepool_file_nodepool_yaml_src: "{{ labkeeper_config_git_dest }}/nodepool/allinone-nodepool.yaml.j2"
        nodepool_clouds_src: "{{ labkeeper_config_git_dest }}/nodepool/openlab-clouds.yaml.j2"
    zuul:
      children:
        zuul-scheduler:
          children:
            zuul-scheduler-master:
              hosts: allinone01
            zuul-scheduler-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-executor:
          children:
            zuul-executor-master:
              hosts: allinone01
            zuul-executor-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-web:
          children:
            zuul-web-master:
              hosts: allinone01
            zuul-web-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-merger:
          children:
            zuul-merger-master:
              hosts: allinone01
            zuul-merger-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-fingergw:
          children:
            zuul-fingergw-master:
              hosts: allinone01
            zuul-fingergw-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-log-server:
          children:
            logserver-master:
              hosts: allinone01
            logserver-slave:
              hosts: allinone02
              vars:
                service_state: stopped
        zuul-master:
          hosts: allinone01
          vars:
            zuul_public_ip: 80.158.7.1
        zuul-slave:
          hosts: allinone02
          vars:
            zuul_public_ip: 80.158.7.2
      vars:
        github_app_id: 7102
        github_app_key_file: "{{ labkeeper_config_git_dest }}/zuul/github-app-liu-openlab-ci.pem"
        # Github app secret
        github_webhook_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65633963633835333432666238626638383938316433303663666333343639643733363862346566
          3363393730343335373261663533303361316430373861370a346663396338336135616538646635
          65326433343366363030393862396336393866336337366265303532636461633064356235313133
          6232353665643934620a613937663931396337363232313065653031623234336332336533376233
          3432
        zuul_file_main_yaml_src: "{{ labkeeper_config_git_dest }}/zuul/allinone-main.yaml"
        #github_acc_token:
        #github_zuul_ssh_key_name: "pub key for openlaballinone"
        zuul_tenant_name: openlaballinone
        openlab_zuul_jobs_key_src: "{{ labkeeper_config_git_dest }}/zuul/allinone-openlab-zuul-jobs.pem"
        openlab_zuul_jobs_key_dest: "/var/lib/zuul/keys/secrets/project/github/liu-sheng/openlab-zuul-jobs/0.pem"
    gear:
      children:
        gear-master:
          hosts: allinone01
        gear-slave:
          hosts: allinone02
          vars:
            service_state: stopped
    statsd:
      children:
        statsd-master:
          hosts: allinone01
        statsd-slave:
          hosts: allinone02
          vars:
            service_state: stopped
    zookeeper:
      children:
        zk-master:
          hosts: allinone01
          vars:
            zk_myid: 1
        zk-slave:
          hosts: allinone02
          vars:
            zk_myid: 2
        zk-03:
          hosts: zk03
          vars:
            zk_myid: 3
    mysql:
      children:
        mysql-master:
          hosts: allinone01
          vars:
            mysql_server_id: 1
        mysql-slave:
          hosts: allinone02
          vars:
            mysql_server_id: 2
    apache:
      children:
        apache-master:
          hosts: allinone01
        apache-slave:
          hosts: allinone02
          vars:
            service_state: stopped

    keepalived:
      children:
        keepalived-master:
          hosts: allinone01
        keepalived-slave:
          hosts: allinone02
