all:
  hosts:
    bastion:
      ansible_connection: local
    nodepool01:
      ansible_host: 10.3.0.17
    zuul01:
      ansible_host: 10.3.0.15
  vars:
    zuul_tenant_name: openlab
    labsync_enabled: true
  children:
    nodepool:
      children:
        nodepool-builder:
          hosts: nodepool01
        nodepool-launcher:
          hosts: nodepool01
      vars:
        nodepool_file_nodepool_yaml_src: "{{ labkeeper_config_git_dest }}/nodepool/openlab-nodepool.yaml.j2"
        nodepool_clouds_src: "{{ labkeeper_config_git_dest }}/nodepool/openlab-clouds.yaml.j2"
    zuul:
      children:
        zuul-scheduler:
          hosts: zuul01
        zuul-executor:
          hosts: zuul01
        zuul-web:
          hosts: zuul01
        zuul-merger:
          hosts: zuul01
        zuul-fingergw:
          hosts: zuul01
        zuul-log-server:
          hosts: zuul01
      vars:
        github_app_id: 6778
        github_app_key_file: "{{ labkeeper_config_git_dest }}/zuul/github-app-theopenlab-ci.pem"
        # Github app secret
        github_webhook_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65633963633835333432666238626638383938316433303663666333343639643733363862346566
          3363393730343335373261663533303361316430373861370a346663396338336135616538646635
          65326433343366363030393862396336393866336337366265303532636461633064356235313133
          6232353665643934620a613937663931396337363232313065653031623234336332336533376233
          3432
        zuul_file_main_yaml_src: "{{ labkeeper_config_git_dest }}/zuul/openlab-main.yaml"
        #github_acc_token:
        #github_zuul_ssh_key_name: "pub key for openlab"
        zuul_tenant_name: openlab
        zuul_public_ip: 80.158.7.173
        openlab_zuul_jobs_key_src: "{{ labkeeper_config_git_dest }}/zuul/theopenlab-openlab-zuul-jobs.pem"
        openlab_zuul_jobs_key_dest: "/var/lib/zuul/keys/secrets/project/github/theopenlab/openlab-zuul-jobs/0.pem"
    gear:
      hosts: zuul01
    statsd:
      hosts: zuul01
    zookeeper:
      hosts: nodepool01
    mysql:
      hosts: zuul01
    apache:
      hosts: zuul01
