all:
  hosts:
    bastion:
      ansible_connection: local
    test:
      ansible_host: 127.0.0.1
  vars:
    zuul_tenant_name: test
    new_zuul_user_key: true
  children:
    nodepool:
      children:
        nodepool-builder:
          hosts: test
        nodepool-launcher:
          hosts: test
      vars:
        nodepool_file_nodepool_yaml_src: "{{ labkeeper_config_git_dest }}/nodepool/fake-nodepool.yaml.j2"
        nodepool_clouds_src: "{{ labkeeper_config_git_dest }}/nodepool/fake-clouds.yaml.j2"
    zuul:
      children:
        zuul-scheduler:
          hosts: test
        zuul-executor:
          hosts: test
        zuul-web:
          hosts: test
        zuul-merger:
          hosts: test
        zuul-fingergw:
          hosts: test
        zuul-log-server:
          hosts: test
      vars:
        github_app_id: 0000
        github_webhook_token: "test"
        zuul_tenant_name: test
        zuul_public_ip: ""
        openlab_zuul_jobs_key_dest: "/var/lib/zuul/keys/secrets/project/github/liu-sheng/openlab-zuul-jobs/0.pem"
    gear:
      hosts: test
    statsd:
      hosts: test
    zookeeper:
      hosts: test
    mysql:
      hosts: test
    apache:
      hosts: test
