- tenant:
    name: openlaballinone
    source:
      github:
        config-projects:
          - liu-sheng/project-config:
              shadow: liu-sheng/openlab-zuul-jobs
              exclude-unprotected-branches: true
          - liu-sheng/openlab-zuul-jobs:
              exclude-unprotected-branches: true
        untrusted-projects:
          # Order matters, load common job repos first
          - liu-sheng/zuul-jobs:
              shadow: liu-sheng/project-config
              exclude-unprotected-branches: true
          # For testing purpose
          #- liu-sheng/gophercloud:
          #    exclude-unprotected-branches: true
          - liu-sheng/machine:
              exclude-unprotected-branches: true
          - liu-sheng/huaweicloud-service-broker:
              exclude-unprotected-branches: true
          - liu-sheng/manageiq-providers-openstack:
              exclude-unprotected-branches: true
          - liu-sheng/terraform-provider-huaweicloud:
              exclude-unprotected-branches: true
          - liu-sheng/origin:
              exclude-unprotected-branches: true
          - liu-sheng/spark:
              exclude-unprotected-branches: true
          - moo-ai/moo-ai.github.io
          - Yikun/arm-openlab-test
          - h00130372/charts
      openstack-git:
        untrusted-projects:
          - include: []
            projects:
              - openstack/openstacksdk
              - openstack-infra/shade
