- tenant:
    name: openlaballinone
    source:
      github:
        config-projects:
          - liu-sheng/project-config:
              shadow: liu-sheng/openlab-zuul-jobs
              exclude-unprotected-branches: true
          - liu-sheng/openlab-zuul-jobs:
              exclude-unprotected-branches: true
        untrusted-projects:
          # Order matters, load common job repos first
          - liu-sheng/zuul-jobs:
              shadow: liu-sheng/project-config
              exclude-unprotected-branches: true
          # For testing purpose
          - gophercloud/gophercloud:
              exclude-unprotected-branches: true
          - liu-sheng/gophercloud:
              exclude-unprotected-branches: true
          - liu-sheng/misty:
              exclude-unprotected-branches: true
          - liu-sheng/cf-openstack-validator:
              exclude-unprotected-branches: true
          - liu-sheng/cf-acceptance-tests:
              exclude-unprotected-branches: true
          - liu-sheng/bosh-acceptance-tests:
              exclude-unprotected-branches: true
          - liu-sheng/terraform-provider-openstack:
              exclude-unprotected-branches: true
          - liu-sheng/ansible
      openstack-git:
        untrusted-projects:
          - include: []
            projects:
              - openstack/openstacksdk
              - openstack-infra/shade
