- tenant:
    name: openlab
    source:
      github:
        config-projects:
          - theopenlab/openlab-zuul-jobs:
              exclude-unprotected-branches: true
          - theopenlab/project-config:
              shadow: theopenlab/openlab-zuul-jobs
              exclude-unprotected-branches: true
        untrusted-projects:
          # Order matters, load common job repos first
          - theopenlab/zuul-jobs:
              shadow: theopenlab/project-config
              exclude-unprotected-branches: true

          # Offical
          # NOTE gophercloud and terraform master are not
          # protected branches
          - gophercloud/gophercloud
          - terraform-providers/terraform-provider-openstack
          - flystack/misty
          - fog/fog-openstack
          - dtantsur/rust-openstack
          - kubernetes/cloud-provider-openstack:
              exclude-unprotected-branches: true
          - theopenlab/ansible:
              exclude-unprotected-branches: true
          - theopenlab/packer:
              exclude-unprotected-branches: true
          - theopenlab/machine:
              exclude-unprotected-branches: true
          - zhongjun2/bosh-huaweicloud-cpi-release:
              exclude-unprotected-branches: false
          - zhongjun2/cf-huaweicloud-validator:
              exclude-unprotected-branches: true
          - liu-sheng/bosh-acceptance-tests:
              exclude-unprotected-branches: true
          - huaweicloud/huaweicloud-service-broker:
              exclude-unprotected-branches: true
          - openservicebrokerapi/osb-checker

      openstack-git:
        untrusted-projects:
          - include: []
            projects:
              - openstack/openstacksdk
              - openstack-infra/shade
