- src: git+https://opendev.org/windmill/ansible-role-diskimage-builder
  name: openstack.diskimage-builder

- src: git+https://opendev.org/windmill/ansible-role-gear
  name: openstack.gearman

- src: git+https://opendev.org/windmill/ansible-role-logrotate
  name: openstack.logrotate

- src: git+https://opendev.org/windmill/ansible-role-nodepool
  name: openstack.nodepool

- src: git+https://opendev.org/x/ansible-role-shade
  name: openstack.shade

- src: git+https://opendev.org/windmill/ansible-role-ssh
  name: openstack.ssh

- src: git+https://opendev.org/windmill/ansible-role-statsd
  name: openstack.statsd

- src: git+https://opendev.org/windmill/ansible-role-sudoers
  name: openstack.sudoers

- src: git+https://opendev.org/windmill/ansible-role-virtualenv
  name: openstack.virtualenv

- src: git+https://opendev.org/windmill/ansible-role-zookeeper
  name: openstack.zookeeper

- src: git+https://opendev.org/windmill/ansible-role-zuul
  name: openstack.zuul

- src: git+https://opendev.org/windmill/ansible-role-openstacksdk
  name: openstack.openstacksdk
