# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install zuul-executor
  hosts: zuul-executor

  tasks:
    - name: Git clone zuul (workaround).
      git:
        dest: "{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/zuul"
        repo: https://git.openstack.org/openstack-infra/zuul

    - name: Install zuul using pip (workaround).
      become: yes
      pip:
        executable: pip3
        name: "file://{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/zuul"
        editable: yes

    - name: Setup openstack.zuul role
      include_role:
        name: openstack.zuul
      vars:
        zuul_file_zuul_executor_service_config_manage: true
        zuul_file_zuul_executor_service_manage: true
        zuul_service_zuul_executor_enabled: yes
        zuul_service_zuul_executor_manage: true
        zuul_service_zuul_executor_state: started
        zuul_task_manager:
          - pre
          - config
          - service

    # TODO(pabelanger): If we want to support xenial, we'll need to use this ppa
    # since bubblewrap doesn't exist.
    - name: Add openstack-infra PPA for bubblewrap
      become: yes
      apt_repository:
        repo: ppa:openstack-ci-core/bubblewrap
      when:
        - ansible_distribution_release | lower == "xenial"

    # TODO(pabelanger): I'm thinking we should likely create
    # ansible-role-bubblewrap to allow user to better manage this dependency.
    - name: Ensure bubblewrap is installed
      become: yes
      package:
        name: bubblewrap
        state: installed

    - name: Setup openstack.logrotate role
      include_role:
        name: openstack.logrotate
      vars:
        logrotate_configs:
          - name: zuul-executor
            log: /var/log/zuul/executor-debug.log /var/log/zuul/executor.log
            options:
              - compress
              - missingok
              - rotate 7
              - daily
              - notifempty

  post_tasks:
    - name: Run zuul-executor validation
      include_role:
        name: test.zuul-executor
