# Copyright 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Install zuul
  hosts: zuul
  become: yes
  tasks:
    # NOTE(pabelanger): Because of ordering issues create the required home
    # directory first.
    - name: Create zuul user directories.
      include_role:
        name: openstack.zuul
      vars:
        zuul_task_manager:
          - pre

    - name: Copy github app key file into place.
      copy:
        dest: /var/lib/zuul/openlab-app-key.pem
        group: zuul
        mode: 0600
        owner: zuul
        src: "{{ github_app_key_file }}"
      when: github_app_key_file is defined

    - name: Create zuul SSH directory.
      file:
        dest: "/var/lib/zuul/.ssh/"
        group: "zuul"
        mode: 0700
        owner: "zuul"
        state: directory

    - name: Copy zuul user SSH keys to zuul home
      copy:
        dest: "/var/lib/zuul/.ssh/{{ item }}"
        group: zuul
        mode: 0600
        owner: zuul
        src: "{{ windmill_config_git_dest }}/zuul/{{ item }}"
      with_items:
        - id_rsa
        - id_rsa.pub

    - name: ensure github.com is a known host
      lineinfile:
        dest: /var/lib/zuul/.ssh/known_hosts
        group: "zuul"
        owner: "zuul"
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
        regexp: "^github\\.com"

    - name: Read zuul SSH public key.
      shell: cat /var/lib/zuul/.ssh/id_rsa.pub
      register: ssh_pub_key

    - name: add zuul SSH public key to github
      github_key:
        name: pub key from openlab CI
        force: yes
        pubkey: '{{ ssh_pub_key.stdout }}'
        token: '{{ github_acc_token }}'
      when: github_acc_token is defined
