# Copyright 2016 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
# labkeeper.zuul
zuul_file_zuul_conf_src: "{{ labkeeper_config_git_dest }}/zuul/zuul.conf.j2"

zuul_install_method: git
zuul_git_dest: "/opt/src/zuul"
zuul_pip_editable: yes

# Disable all services as default
zuul_file_zuul_fingergw_service_config_manage: false
zuul_file_zuul_fingergw_service_manage: false
zuul_service_zuul_fingergw_manage: false

zuul_file_zuul_merger_service_config_manage: false
zuul_file_zuul_merger_service_manage: false
zuul_service_zuul_merger_manage: false

zuul_file_zuul_scheduler_service_config_manage: false
zuul_file_zuul_scheduler_service_manage: false
zuul_service_zuul_scheduler_manage: false

zuul_file_zuul_web_service_config_manage: false
zuul_file_zuul_web_service_manage: false
zuul_service_zuul_web_manage: false

zuul_file_zuul_executor_service_config_manage: false
zuul_file_zuul_executor_service_manage: false
zuul_service_zuul_executor_manage: false

# do not enable zuul service as default
zuul_service_zuul_executor_enabled: false
zuul_service_zuul_fingergw_enabled: false
zuul_service_zuul_merger_enabled: false
zuul_service_zuul_scheduler_enabled: false
zuul_service_zuul_web_enabled: false

zuul_file_zuul_executor_service_config_src: zuul/etc/systemd/system/zuul-executor.service.d/override.conf.j2
zuul_file_zuul_merger_service_config_src: zuul/etc/systemd/system/zuul-merger.service.d/override.conf.j2
zuul_file_zuul_scheduler_service_config_src: zuul/etc/systemd/system/zuul-scheduler.service.d/override.conf.j2
zuul_file_zuul_web_service_config_src: zuul/etc/systemd/system/zuul-web.service.d/override.conf.j2

zuul_status_host: "https://status.openlabtesting.org"
zuul_status_url: "{{ zuul_status_host }}/builds?project={change.project}&change={change.number},{change.patchset}&pipeline={pipeline.name}"
